### ISSUE TITLE
The normalization of `new Decimal(-Infinity)` breaks some operations and may be incorrect

### ISSUE THREAD

**Issue by James103** [Patashu/break_eternity.js#168]
`new Decimal(Infinity)` returns a Decimal object with `{ sign: 1, mag: Infinity, layer: Infinity }`.
`new Decimal(Infintiy).negate()` returns a Decimal object with `{ sign: -1, mag: Infinity, layer: Infinity }`.
Normalizing this with `new Decimal(Infintiy).negate().normalize()`, I get a Decimal object with `{ sign: -1, mag: -Infinity, layer: -Infinity }`.
Running `new Decimal(-Infinity)` directly also returns a Decimal object with `{ sign: -1, mag: -Infinity, layer: -Infinity }`.

Either the normalization of `new Decimal(-Infinity)` should be a Decimal object with `{ sign: -1, mag: Infinity, layer: Infinity }`, or functions operating on Decimals should be changed to handle Decimals consisting of `{ sign: -1, mag: -Infinity, layer: -Infinity }`.

Originally found in https://mathcookie17.github.io/Eternal-Notations/, by navigating to that page, opening a browser console for that page, and running the command `formatAll(new Decimal(-Infinity))` there.

**Comment by MathCookie17** [comment]
I am of the opinion that -Infinity should be {-1, Infinity, Infinity}, but the library was designed with -Infinity as {-1, -Infinity, -Infinity}, so that's what it normalizes to - it just wasn't even registering as -Infinity as all when I had it normalizing to {-1, Infinity, Infinity}. I don't want to cause a breaking change, so despite my judgement, it'll remain as {-1, -Infinity, -Infinity}... so I'll probably need to make a bunch of special cases. I'll look into this at some point.

**Comment by MathCookie17** [comment]
I did an immediate fix for the Eternal Notations issue (i.e. it now detects infinities in a way that sidesteps the break_eternity bug, so -Infinity works there now. Figured I'd note this here since this was kind of an Eternal Notations issue too, though I haven't looked at the actual break_eternity bug yet)

**Comment by MathCookie17** [comment]
...on second thought, there are just too many strange cases that {-1, -Infinity, -Infinity} causes. I'm changing it to {-1, Infinity, Infinity} like it always should have been.
